apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.service.namespace }}
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{.Values.image.imagePullPolicy}}
        ports:
        - containerPort: {{ .Values.service.targetPort}}
        resources:
          requests:
            memory: {{ .Values.service.resources.memoryMiB }}Mi
            cpu: {{ .Values.service.resources.cpuMilli }}m
          limits:
            memory: {{ .Values.service.resources.memoryMiB }}Mi
            cpu: {{ .Values.service.resources.cpuMilli }}m
